CREATE OR REPLACE TRIGGER primary_key_trigger
BEFORE INSERT ON account
FOR EACH ROW
DECLARE
    a account.accountno%TYPE;
BEGIN
    IF (:NEW.accountno IS NULL) THEN
        RAISE_APPLICATION_ERROR(-20002, 'PRIMARY KEY VIOLATION BECAUSE IT CANNOT BE NULL');
    END IF;

    SELECT accountno INTO a FROM account WHERE accountno = :NEW.accountno;
    RAISE_APPLICATION_ERROR(-20003, 'PRIMARY KEY VIOLATION BECAUSE IT SHOULD BE UNIQUE');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
END;

-- primary key violation
